// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const CustomerIssue = sequelize.define('customerIssue', {
    owner: {
      type: DataTypes.STRING,
    },
    state: {
      type: DataTypes.ENUM('open','closed','pending_return','pending_refund','refunded','declined'),
    },
    type: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    closedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'customer_issue',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  CustomerIssue.associate = (models) => {
    CustomerIssue.belongsTo(models.syliusOrder, {
      foreignKey: {
        name: 'orderIdKey',
        field: 'order_id',
      },
      as: 'order',
    });
    CustomerIssue.hasMany(models.customerIssueSupport, {
      foreignKey: {
        name: 'customerIssueIdKey',
        field: 'customer_issue_id',
      },
      as: 'customerIssueCustomerIssueSupports',
    });
    CustomerIssue.hasOne(models.transaction, {
      foreignKey: {
        name: 'customerIssueIdKey',
        field: 'customer_issue_id',
      },
      as: 'customerIssueTransaction',
    });
  };

  return CustomerIssue;
};
