// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const StorageUnit = sequelize.define('storageUnit', {
    aisle: {
      type: DataTypes.STRING,
    },
    row: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    box: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    quantity: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    storageType: {
      type: DataTypes.ENUM('free','bags','boxes','palets'),
      allowNull: false,
    },
    isFlagged: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP'),
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    deletedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'storage_unit',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  StorageUnit.associate = (models) => {
    StorageUnit.belongsTo(models.warehouse, {
      foreignKey: {
        name: 'warehouseIdKey',
        field: 'warehouse_id',
      },
      as: 'warehouse',
    });
    StorageUnit.belongsTo(models.syliusProduct, {
      foreignKey: {
        name: 'productIdKey',
        field: 'product_id',
      },
      as: 'product',
    });
  };

  return StorageUnit;
};
