// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const SyliusOrder = sequelize.define('syliusOrder', {
    number: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    total: {
      type: DataTypes.DOUBLE,
      allowNull: false,
    },
    state: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    owner: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP'),
    },
  }, {
    tableName: 'sylius_order',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  SyliusOrder.associate = (models) => {
    SyliusOrder.belongsTo(models.syliusCustomer, {
      foreignKey: {
        name: 'customerIdKey',
        field: 'customer_id',
      },
      as: 'customer',
    });
    SyliusOrder.hasMany(models.syliusOrderItem, {
      foreignKey: {
        name: 'orderIdKey',
        field: 'order_id',
      },
      as: 'orderSyliusOrderItems',
    });
    SyliusOrder.hasMany(models.syliusPayment, {
      foreignKey: {
        name: 'orderIdKey',
        field: 'order_id',
      },
      as: 'orderSyliusPayments',
    });
    SyliusOrder.hasMany(models.syliusShipping, {
      foreignKey: {
        name: 'orderIdKey',
        field: 'order_id',
      },
      as: 'orderSyliusShippings',
    });
  };

  return SyliusOrder;
};
